#!/usr/bin/env python3
"""
append_gate_ledger.py — record today's gate decisions in the append-only ledger.

`output/ledger/Gate_Ledger.csv` is the system's only durable memory. Everything
else under `output/` is regenerated by the next run, so a decision that is not
in the ledger survives exactly as long as its evaluation file does — which is
not long: `evaluation_2026-08-22.md` was destroyed by an agent writing through a
symlink, in a tree with no VCS, and those decisions are simply gone.

THE LEDGER LISTENS; IT DOES NOT REVIEW. The evaluation it reads has already been
through `tools/eval_reviewer.py` and the Reviewer subagent, and is only on disk
because it passed. A second, human review gate here was tried between 2026-08-18
and 2026-08-23 and failed in both directions at once: the drafts for 18, 19 and
20 Aug were never committed (38 rows lost, one file silently corrupt), while
every row that did land on 23 Aug went in still carrying its "edit before
--commit" marker. A control nobody operates is not protecting anything, and this
one was costing the ledger the coverage it exists to provide.

So this script writes straight to the ledger:

  1. `python3 tools/append_gate_ledger.py`
       reads output/.state/eval_manifest_<date>.json `gates[]` when the Trader
       emitted one (the supported path), else falls back to parsing today's
       evaluation, then validates and writes. Exits 2 rather than 0 if the board
       cannot be read at all.
  2. `--dry-run` prints exactly what would be written and touches nothing.

THE ONE MUTABLE CASE. Rows dated `<date>` whose `Source` is `daily-eval` are
replaced on each run, so a same-day re-run corrects its own record instead of
laying a second opinion beside the first. Every other row is immutable —
including a hand-entered position dated today, which is why the filter tests
`Source` as well as `Date` and not just the line prefix the way
`tools/rerun.py:strip_ledger_rows` does (that one is undoing a whole day, and
means to take the lot).

VALIDATION IS TWO TESTS, AND IT REFUSES THE BATCH. `Action` must be in the
ledger's vocabulary, and `Qty` must be empty — this script never writes a size
(positions are entered by hand from contract notes), so a populated `Qty` means
the CSV fields have shifted, which is exactly what happened to
`pending_2026-08-20.csv`. Either failure prints the offending rows and exits
non-zero without writing, and the daily run halts on non-zero like any other
step. There is deliberately no quarantine file: that is the waiting room again,
under a new name.

WHAT COUNTS AS NON-TRIVIAL. Signals containing BUY-TRIGGER, STARTER, BUY,
SELL, EXIT, TRIM, BLOCKED or WAIT record a row. HOLD / AVOID / VERIFY do not
— they are the steady-state majority and would bury the decisions the ledger
exists to audit. Adjust ACTIONABLE below if your vocabulary grows, and keep
it ordered most-specific-first: the match takes the first hit.

Standard library only.
"""

import argparse
import csv
import shutil
import datetime
import json
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUTPUT_DIR = os.environ.get("TP_OUTPUT", os.path.join(ROOT, "output"))
LEDGER = os.path.join(OUTPUT_DIR, "ledger", "Gate_Ledger.csv")
STATE_DIR = os.path.join(OUTPUT_DIR, ".state")

SOURCE = "daily-eval"          # rows this script owns, and the only ones it replaces

COLUMNS = ["Date", "Ticker", "Account", "Source", "Gate_Result", "Action",
           "Qty", "Avg_Entry", "Ccy", "Price_At_Decision", "Status",
           "Exit_Date", "Exit_Price", "Notes"]

# ORDER IS THE CONTRACT — matched most-specific-first, not tuple-first.
# `next(a for a in ACTIONABLE if a in sig_up)` returns the FIRST hit, so a plain
# "BUY" listed ahead of "BUY-TRIGGER" silently rewrites `🔵 BUY-TRIGGER (STARTER)`
# — a conditional that has not filled — as `BUY`, which is not even a term the
# ledger uses (its vocabulary is ENTERED / BUY-TRIGGER / BLOCKED / WAIT / ...).
# Into an append-only audit file that is a permanent misstatement of what was
# decided. Keep compounds ahead of their own prefixes.
ACTIONABLE = ("BUY-TRIGGER", "STARTER-CAP", "BLOCKED", "STARTER",
              "SELL", "EXIT", "TRIM", "WAIT", "BUY")


def today():
    return datetime.date.today().isoformat()


def eval_path(date):
    return os.path.join(OUTPUT_DIR, f"evaluation_{date}.md")


def parse_price(px):
    """('123.45', 'USD'|'GBp'|'GBP'|'CAD'|'EUR'|'') from '$97.05' / '1263p' / 'C$30.22'.

    C$ is checked before $ — a Toronto line like KNT.TO renders 'C$30.22', and a
    plain startswith('$') test both misses it and silently books the row as
    currency-less, which is worse than USD: it reaches the ledger with a bare
    number and no unit.
    """
    s = (px or "").strip()
    if s.startswith("C$"):
        return s[2:].replace(",", ""), "CAD"
    if s.startswith("€"):
        return s[1:].replace(",", ""), "EUR"
    if s.startswith("$"):
        return s[1:].replace(",", ""), "USD"
    if s.startswith("£"):
        return s[1:].replace(",", ""), "GBP"
    if re.fullmatch(r"[\d,.]+p", s):
        return s[:-1].replace(",", ""), "GBp"
    return re.sub(r"[^\d.]", "", s), ""


BOARD_RE = re.compile(r"^##\s+Conviction-ranked action board\s*$(.*?)(?=^##\s|\Z)",
                      re.M | re.S | re.I)

# A PERIOD ENDS THE CLAUSE ONLY WHEN IT ENDS A SENTENCE.
# The clause runs to the first sentence period or semicolon, with parenthesised
# spans passed over whole. It used to run to the first period of any kind, which
# is fine until a gate note contains a number or a ticker — and they nearly all
# do. On 2026-08-24 LNG's card reached the ledger as the permanent, meaningless
# string "GATE: S fail #6 only (AT-PEAK) — ... LNG is +11", severed mid-decimal
# at the "." of "+11.3%"; the same edge truncates "trigger 9.09p" to "trigger 9"
# and "IUES.L" to "IUES". A truncated gate result is worse than an absent one:
# it is indistinguishable from a short verdict that was written that way, in the
# one file that is never regenerated. `\.(?!\s|$)` keeps decimals and dotted
# tickers, and still stops at ". " and at end-of-field.
GATE_CLAUSE = r"(?:[^.;()]|\.(?!\s|$)|\([^)]*\))*"



def board_section(body):
    """The 8-column per-sector board, or None if it cannot be resolved.

    Returns None both when the heading is absent and when it appears more than
    once — an ambiguous match is the bug this function exists to stop, not
    something to resolve by taking the first hit.
    """
    hits = BOARD_RE.findall(body)
    return hits[0] if len(hits) == 1 else None


def parse_actions(body, date):
    """Draft rows from the conviction-ranked board's per-sector tables.

    FALLBACK ONLY — `rows_from_sidecar` is the supported path. Parsing the
    report's prose is what produced the four-day silent outage (2026-08-20..23):
    the report carries two board-ish headings, the old regex was case-sensitive
    against a spelling the template does not use, and `re.search` bound it to a
    3-column summary that an 8-column row regex could never match. It returned
    [] and exit 0 while 14 actionable rows a day went unrecorded.

    Raises LookupError when the board cannot be resolved, so "could not read it"
    can never again be mistaken for "there was nothing to read".
    """
    board = board_section(body)
    if board is None:
        raise LookupError(
            "cannot locate exactly one '## Conviction-ranked action board' "
            "section in the evaluation (missing, renamed, or duplicated)")
    rows = []
    for sec_m in re.finditer(r"^### (.+?)$(.*?)(?=^### |\Z)", board, re.M | re.S):
        sector, block = sec_m.group(1).strip(), sec_m.group(2)
        for row_m in re.finditer(
                r"^\|\s*\*{0,2}([A-Z0-9.\-]+)\*{0,2}\s*\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|([^|]*)\|",
                block, re.M):
            ticker, _c2, _c3, _c4, _c5, _c6, signal, _note = row_m.groups()
            ticker = ticker.strip()
            if ticker.lower() in ("ticker", "---", "gate"):
                continue
            sig_up = signal.upper()
            if not any(a in sig_up for a in ACTIONABLE):
                continue
            action = next(a for a in ACTIONABLE if a in sig_up)
            px = _c2.strip()
            price, ccy = parse_price(px)
            gate = ""
            ng = re.search(r"GATE:\s*[SE]" + GATE_CLAUSE, _note)
            if ng:
                gate = ng.group(0).strip()
            if not gate:
                para = re.search(r"\*\*" + re.escape(ticker) + r"\*\*\s*—\s*(.+)",
                                 block)
                if para:
                    g = re.search(r"GATE\s+[SE]" + GATE_CLAUSE, para.group(1))
                    gate = g.group(0).strip() if g else ""
            rows.append({
                "Date": date, "Ticker": ticker, "Account": "A",
                "Source": SOURCE, "Gate_Result": gate,
                "Action": action, "Qty": "", "Avg_Entry": "", "Ccy": ccy,
                "Price_At_Decision": price, "Status": "OPEN",
                "Exit_Date": "", "Exit_Price": "",
                "Notes": (f"[{sector}] signal {signal.strip()} — from "
                          f"evaluation_{date}.md (prose fallback)"),
            })
    return rows


def _degraded(why):
    """Say why the sidecar was refused, then fall back. Always returns None.

    A PRESENT SIDECAR THAT CANNOT BE USED IS NOT THE SAME AS NO SIDECAR, and
    this script's whole history is that distinction going unsaid: the four-day
    outage (2026-08-20..23) was "could not read it" printing as "nothing to
    read". The same shape recurred on 2026-08-24 one layer up — the Trader
    emitted a sidecar with `gates[]` missing entirely, `handoff.py --check-all`
    still reported it ✅ because it validates the envelope and not the field its
    only consumer needs, and the run fell through to the prose parser in
    silence. Nothing was lost that day, but nothing said so either. The origin
    line already names which path ran; this says why the better one did not.
    """
    print(f"note: falling back to the prose parser — {why}", file=sys.stderr)
    return None


def rows_from_sidecar(date):
    """Draft rows from output/.state/eval_manifest_<date>.json, or None.

    THE SUPPORTED PATH. `tools/handoff.py` exists because "a better parser is
    not the fix — not parsing is the fix", and this is the consumer with the
    most to lose from a bad parse: it writes to an append-only file that is
    never regenerated. Absent or unusable sidecar → None, and the caller falls
    back to the parser exactly as every other sidecar consumer does.
    """
    path = os.path.join(STATE_DIR, f"eval_manifest_{date}.json")
    if not os.path.exists(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            payload = json.load(f)
    except (OSError, ValueError):
        return None
    if payload.get("date") != date:
        return _degraded(f"eval_manifest_{date}.json is dated "
                         f"{payload.get('date')!r}, not {date}")
    gates = payload.get("gates")
    if not isinstance(gates, list) or not gates:
        return _degraded(f"eval_manifest_{date}.json has no usable gates[] "
                         f"(key {'absent' if 'gates' not in payload else 'present but empty'})")
    if not any((g or {}).get("signal") for g in gates):
        return _degraded(f"eval_manifest_{date}.json gates[] carry no `signal` "
                         f"field (pre-widening manifest: ticker+card only)")
    rows = []
    for g in gates:
        g = g or {}
        ticker, signal = g.get("ticker"), str(g.get("signal") or "")
        if not ticker or not signal:
            continue
        sig_up = signal.upper()
        if not any(a in sig_up for a in ACTIONABLE):
            continue
        action = next(a for a in ACTIONABLE if a in sig_up)
        px, ccy = g.get("px") or "", g.get("ccy") or ""
        if px and not ccy:
            px, ccy = parse_price(str(px))
        rows.append({
            "Date": date, "Ticker": ticker, "Account": "A",
            "Source": SOURCE, "Gate_Result": g.get("result") or "",
            "Action": action, "Qty": "", "Avg_Entry": "", "Ccy": ccy,
            "Price_At_Decision": str(px), "Status": "OPEN",
            "Exit_Date": "", "Exit_Price": "",
            "Notes": (f"signal {signal.strip()} — from "
                      f"eval_manifest_{date}.json"),
        })
    return rows


KNOWN_ACTIONS = set(ACTIONABLE)


def validate(rows):
    """[(row, why)] for every row that fails a shape test. Empty list = clean.

    Two tests, both cheap, both aimed at the one failure this script has
    actually produced: CSV fields shifting left when an unquoted comma reaches
    the writer. `pending_2026-08-20.csv` came out with Action=" RECORD);
    RS-LEADER" and Qty="BUY-TRIGGER" on 7 of 13 rows. Either test catches all 7.
    """
    bad = []
    for r in rows:
        if r.get("Action") not in KNOWN_ACTIONS:
            bad.append((r, f"Action {r.get('Action')!r} is not in the ledger "
                           f"vocabulary — fields have probably shifted"))
        elif (r.get("Qty") or "").strip():
            bad.append((r, f"Qty {r.get('Qty')!r} is not empty — this script "
                           f"never writes a size, so fields have shifted"))
    return bad


def read_ledger_lines():
    """(header, [raw data lines]) — raw, so untouched rows are never reformatted.

    Line-based on purpose. Round-tripping the whole file through csv would
    renormalise quoting on 80 rows this run has no business editing. The guard
    below is what makes that safe: if any field ever contains a newline the line
    count and the parsed row count diverge, and we refuse rather than shred it.
    """
    if not os.path.exists(LEDGER):
        return ",".join(COLUMNS) + "\n", []
    with open(LEDGER, encoding="utf-8", newline="") as f:
        raw = f.readlines()
    if not raw:
        return ",".join(COLUMNS) + "\n", []
    with open(LEDGER, encoding="utf-8", newline="") as f:
        parsed = list(csv.DictReader(f))
    if len(raw) - 1 != len(parsed):
        raise SystemExit(
            f"refusing to rewrite {os.path.relpath(LEDGER, ROOT)}: "
            f"{len(raw) - 1} line(s) but {len(parsed)} parsed row(s) — a field "
            f"spans a newline and the line-based rewrite would corrupt it")
    return raw[0], raw[1:]


def commit(date, rows, dry=False):
    """Replace this date's own rows with `rows`. Returns (dropped, added, deduped).

    Scoped by Date *and* Source: a position row you entered by hand today is not
    this script's to replace.
    """
    header, data = read_ledger_lines()
    kept, dropped, kept_keys = [], 0, set()
    for ln in data:
        try:
            f = next(csv.reader([ln]))
        except (csv.Error, StopIteration):
            kept.append(ln)             # unparseable: never this script's to touch
            continue
        if len(f) >= 4 and f[0] == date and f[3] == SOURCE:
            dropped += 1
            continue
        kept.append(ln)
        if len(f) >= 6:
            kept_keys.add((f[0], f[1], f[5]))

    # Survivors still win on a key clash — a hand-entered or backfilled row for
    # the same Date+Ticker+Action is the better record of the two.
    fresh = [r for r in rows
             if (r["Date"], r["Ticker"], r["Action"]) not in kept_keys]
    deduped = len(rows) - len(fresh)

    if dry:
        return dropped, len(fresh), deduped

    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=COLUMNS, lineterminator="\n")
    for r in fresh:
        w.writerow({k: r.get(k, "") for k in COLUMNS})

    os.makedirs(os.path.dirname(LEDGER), exist_ok=True)
    if os.path.exists(LEDGER):
        # One backup, every write. This tree has no VCS and the ledger is the
        # only copy of most of what is in it.
        shutil.copy2(LEDGER, LEDGER + ".bak")
    tmp = LEDGER + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(header)
        f.writelines(kept)
        f.write(buf.getvalue())
    os.replace(tmp, LEDGER)
    return dropped, len(fresh), deduped


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1].strip())
    ap.add_argument("--date", default=today())
    ap.add_argument("--dry-run", action="store_true",
                    help="print what would be written; touch nothing")
    a = ap.parse_args()

    src = eval_path(a.date)
    if not os.path.exists(src):
        print(f"no evaluation for {a.date} at {os.path.relpath(src, ROOT)}",
              file=sys.stderr)
        return 1

    # THREE OUTCOMES, THREE EXITS. These used to print one message and return 0:
    # "no actionable rows found (or all already in the ledger)". A broken parse,
    # a genuinely quiet day and a fully-deduped day were indistinguishable to
    # the caller and to tools/checks.py, which is how a four-day outage stayed
    # silent. Keep them apart.
    rows = rows_from_sidecar(a.date)
    if rows is not None:
        origin = f"eval_manifest_{a.date}.json"
    else:
        try:
            rows = parse_actions(open(src, encoding="utf-8").read(), a.date)
        except LookupError as e:
            print(f"cannot record: {e}\n"
                  f"  the evaluation is on disk but its action board could not "
                  f"be read, so 'nothing to record' cannot be trusted.\n"
                  f"  fix the heading, or have the Trader emit gates[] with "
                  f"`signal` in output/.state/eval_manifest_{a.date}.json.",
                  file=sys.stderr)
            return 2
        origin = f"evaluation_{a.date}.md (prose fallback)"

    bad = validate(rows)
    if bad:
        print(f"refusing to write {len(bad)} malformed row(s) from {origin} — "
              f"nothing was changed:", file=sys.stderr)
        for r, why in bad:
            print(f"  {r.get('Date')} {r.get('Ticker')}: {why}", file=sys.stderr)
        return 1

    dropped, added, deduped = commit(a.date, rows, dry=a.dry_run)

    what = "would write" if a.dry_run else "wrote"
    tail = f", {deduped} already recorded by another source" if deduped else ""
    print(f"{what} {added} row(s) from {origin}"
          + (f", replacing {dropped} earlier {SOURCE} row(s) for {a.date}"
             if dropped else "")
          + tail)
    if a.dry_run:
        w = csv.DictWriter(sys.stdout, fieldnames=COLUMNS, lineterminator="\n")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in COLUMNS})
    else:
        print(f"→ {os.path.relpath(LEDGER, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
